### ISSUE TITLE
Feature Request: Infinite Scrolling

### ISSUE THREAD

**Issue by PreciselyAlyss** [bigcommerce/cornerstone#1077]
### Description
There is a desire to have a "View All" option for products within categories or brands. There are some performance limitations on this, such as trying to load 1000 products on the same page. When a category is too large to perform this function well, it would be ideal to hide "View All" or change it to a lower upper limit such as "View 250". 

### Mockups
![image](https://user-images.githubusercontent.com/9373485/29686249-dfacd30a-88dd-11e7-9c97-24cd5366a228.png)

### Links 
You must sign into the forum to view the link below
- [Ability to view all in a product listing page](http://ideas.bigcommerce.com/forums/178746-bigcommerce-ideas/suggestions/3404480-ability-to-view-all-in-a-product-listing-page)

### Suggested options
Implement lazyloading such as 
- [blazy npm](https://www.npmjs.com/package/blazy)

**Comment by bookernath** [comment]
We don't plan on adding "view all" the platform any time soon for performance reasons.

For folks that are interested in this sort of UX, I'd recommend implementing an infinite scroll library; there are many good options available on NPM which could be integrated on a Stencil theme.

Due to lack of much interest on this issue so far, we don't plan on implementing this natively in our Cornerstone reference theme for now, so we'll close this issue.

**Comment by nowlena** [comment]
For reference, [IntuitSolutions ](https://www.intuitsolutions.net/)has an Infinite Scroll solution for anyone using a Stencil theme. Please reach out to us for more information :)
