### ISSUE TITLE
Product options and actions are not visible in Google AMP

### ISSUE THREAD

**Issue by taruntds** [bigcommerce/cornerstone#1388]
Hello @karen-white 

I have AMP compatible stencil theme and when i visit the product page it doesn't show any options and add to cart button to proceed further. 

Anyone has fixed this issue, please let me know. I have tried to copy paste the same file from latest version to mine current theme.

**Comment by taruntds** [comment]
@aisflat439 older cornerstone version 1.4.0

**Comment by taruntds** [comment]
@Ubersmake @aisflat439 

I am facing this issue. "Origin of <amp-iframe> must not be equal to container". How can i fix this issue.

**Comment by junedkazi** [comment]
@taruntds can you reproduce it with the latest cornerstone ? If it is a fork off of cornerstone can you share store url and the broken url in an email. You mail it to me at my firstname.lastname@bigcommerce.com. I can take a quick look at it first thing Monday.

**Comment by taruntds** [comment]
Hello @junedkazi,

I tried to mail you but it didn't send, may be your email address is not correct.

Regarding the issue, i have mentioned in detail.

AMP Store URL: **https://www.marquis-wines.com/amp/angove-2017-organic-cabernet-sauvignon-750ml/**

I have figured out the issue and also compared with latest cornerstone theme. There is a product option handlebar(**{{product.amp_options_url}}**) which is showing the full path URL in cornerstone where in above link it is only showing the product URL('**/products.php?type=amp_product_options&productId=9666**').

I have also compared amp files from cornerstone. Can you please help me.

**Comment by bookernath** [comment]
@taruntds currently, we don't support using AMP on the canonical, because the amp-iframe will not load if it comes from the same host as the parent page.

You should be able to see it load by viewing the page from the AMP cache: https://cdn.ampproject.org/c/s/www.marquis-wines.com/amp/angove-2017-organic-cabernet-sauvignon-750ml/

This is also how it will show when viewed from a Google search result.

We're not very happy with this limitation of amp-iframe (and we've seen some other user experience issues related to it), so there's some work underway at the moment to try to replace our usage of amp-iframe for product options display with another method. I'll make a note to comment back to this thread when we have something to announce there.

Once we've removed our dependency on amp-iframe, we should be able to support AMP browsing directly on the storefront (instead of just from Google search results).

Let me know if you have questions! Thanks.

**Comment by taruntds** [comment]
Hello @bookernath 

Thank you for replying me back for this issue. 

I am still hoping if there is any other way to fix this issue.

**Comment by taruntds** [comment]
Hello @karen-white,

Any update on this request.

**Comment by bookernath** [comment]
We have no near-term plans to "fix" this since this is an unsupported usage of Google AMP at this time. We only officially support AMP pages via the AMP cache as mentioned in an earlier comment.

If we broaden our support in a future Cornerstone release, we'll make mention of it in release notes and other communications.
