### ISSUE TITLE
{{{json cart}} returns a blank space, used to work completely fine

### ISSUE THREAD

**Issue by wallybold** [bigcommerce/cornerstone#1425]
### Expected behavior
`{{{json cart.items}}}` returns a json representation of the cart, if not available, returns {} (or really anything syntactically valid would be okay)

### Actual behavior
`{{{json cart.items}}}` returns a blank space and breaks javascript

### Steps to reproduce behavior
1. Get the newest version of cornerstone
2. Use the `{{{json cart.items}}}` filter somewhere in the theme (my case was in the script manager)
  a. Specific example I did was similar to `window.variable = `{{{json cart.items}}} || {}`
3. Navigate to a non-cart page, there will be a syntax error.

**Comment by bookernath** [comment]
Hi @wallybold -

In Cornerstone 3.0, we removed the cart resource from rendering in the theme by default. This is because the Cart can be quite an expensive resource to compute on the backend (especially for large carts and stores with certain configurations). We've moved all of our Cart interactions to use frontend API calls (AJAX) to improve the performance of stores.

However, you can still turn the cart resource back on by flipping [this flag](https://github.com/bigcommerce/cornerstone/blob/master/config.json#L327) if you like. It hasn't been deprecated, we've just changed the default behavior of our theme.

If you want the quickest possible fix, you can simply re-enable `cart` in your `config.json`. However, you might also consider using the [Storefront Cart API](https://developer.bigcommerce.com/api-docs/cart-and-checkout/cart-and-checkout-overview#cart-checkout_storefront-cart-and-checkout) (or convenience functions in [stencil-utils](https://github.com/bigcommerce/stencil-utils/blob/master/src/api/cart.js)) if you're also interested in improving the performance of your store.

**Comment by wallybold** [comment]
Hi Nathan, thank you for the quick response! I am in fact an app developer for Bigcommerce and need this to work without external theme changes. Is that possible? I find it strange that even if the cart resource is not available it wouldn't return an empty array or something, but I imagine that has to do more with the `json` filter. Can you think of a quick way to accomplish the same functionality as before without having to do an API call or changing theme code?

**Comment by bookernath** [comment]
@wallybold what sort of functionality are you trying to realize with the Cart resource? It's likely it could use the Cart API instead, which would work on all stores and also allow the functionality to be loaded progressively (maybe) which will offer better guarantees around page load performance.

**Comment by wallybold** [comment]
The only problem with the cart API for me would be the fact that it is an asynchronous call and I am loading in another scripts remotely that depends on the variable. If that is all that is available I could likely make it work though.

**Comment by bookernath** [comment]
That's certainly our recommendation of a best practice for app partners right now. I'd love if you gave it a try, and feel free to contact me if you're running into issues!

**Comment by junedkazi** [comment]
@wallybold I am closing this ticket but please do reopen if we have failed to answer any questions.
