### ISSUE TITLE
[Store Breaking] Customers can't login due to server missbehavior running cornerstone default theme and modified theme

### ISSUE THREAD

**Issue by fthobe** [bigcommerce/cornerstone#1613]
Customers can not login for reasons unidentified by us and BigCommerce. The behavior was reproduced on cornerstone (default template no modifications) as well as our customised theme and seems to be limited to our instance or not yet to be understood as global issue of the platform. 

The issue can be reproduced in a vanilla incognito window by: 
- trying to login into our store using the default login.php page https://www.ricompro.it/login.php

The issue **can not** be reproduced when:
- user logged into backend /manage
- theme preview mode

I am putting @bc-zoharmuzafi cc (@karen-white we miss you ;) as we really desperate and customer support doesn't listen to us resulting in customers not being able to login since 6 days. They refuse to test in incognito and are therefore not able to reproduce the error. 
The problem can only be reproduced on incognito mode as the issue doesn't present itself when being logged in to /manage or using theme preview.  

### Expected behavior
Customers get logged in a cookie is created. Preset Variables get loaded correctly and store functions as expected including customer related websites. Funny enough /checkout is not affected. 

### Actual behavior
For reasons unknown to us the cookie and session are created but the platform refuses to load customer related content (any preset variable or customer related page) effectively  breaking any extension using customer ID or any other customer preset variable.

### Steps to reproduce behavior
Open an incognito window, go to https://www.ricompro.it/login.php and try to login. Customer gets redirected to the log-in and the platform does not interpret the session correctly.

**Comment by obrien-k** [comment]
Hey there @fthobe thanks for bringing this to light, I was able to find some more info after reviewing this with our support team:

The issue described here is due to a setting found on your store in the control panel, within Store Setup -> Store Settings -> Security and Privacy. If "Shopper activity extends logout duration" is set to a custom number of hours, the checkout doesn't work as expected. 

Our Product Support Engineering team created an internal ticket for further investigation and I've ensured your experience has been shared on that ticket as well. The support case you had was also attached on December 26, 2019, so you should receive communications once the internal ticket is closed. To resolve this temporarily, you can disable the custom setting.

**Comment by fthobe** [comment]
Hi @obrien-k , thank you for your answer: 
yes, that was the issue. It would be great if you could communicate the engineering ticket number as well.
