### ISSUE TITLE
checkout.html changes work in development but have no effect in production

### ISSUE THREAD

**Issue by flyingL123** [bigcommerce/cornerstone#1909]
### Expected behavior
If I make a change in `templates/pages/checkout.html` file, I am able to see it as expected when running my theme locally with stencil.

### Actual behavior
After deploying the theme to the live store, I see the single-page optimized checkout as expected, but the change I made is not present.

### Steps to reproduce behavior
In the `checkout.html` file, I add the highlighted line:
![image](https://user-images.githubusercontent.com/2486712/99769802-e5b1cc00-2ad4-11eb-9242-a787b8f15497.png)

View the checkout locally and that new line is visible in the source:

![image](https://user-images.githubusercontent.com/2486712/99769911-1134b680-2ad5-11eb-8776-abe62e6b3e5f.png)

Deploy the checkout to the live website, and the new line is not there:

![image](https://user-images.githubusercontent.com/2486712/99770026-39bcb080-2ad5-11eb-9c4e-17af0856311b.png)

Is there something that would cause these changes to not appear on the live site? My store is set to use "Optimized One-Page Checkout". This method of customizing has been working for me for a while. Did something change that would cause this not to work or is there a bug of some kind?

**Comment by junedkazi** [comment]
@flyingL123 can you confirm you have this added to your features list in the config json
https://github.com/bigcommerce/cornerstone/blob/master/config.json#L34

**Comment by flyingL123** [comment]
@junedkazi 😃 - I was literally just writing a comment that I finally figured it out, and it has to do with that `customized_checkout` being included in the feature list.

I am surprised to discover that. I thought those features were just used for displaying features on the theme's marketplace page. I didn't realize they actually effected functionality. Is that the intended behavior?

Thanks very much for getting back to me about this.

**Comment by junedkazi** [comment]
@flyingL123 it is used for both purposes. In some cases we use it to understand if the theme supports a feature as well which is why we only allow predefined set of keys only rather than free form text.

In case of checkout if the flag exists and if the template file exist it will use the template to render the page or else gracefully fallback to BC default template.

I agree in cases where flags are used to drive theme behavior we need checks in place on stencil cli to warn theme developers. I will create a task internally for the team to look into.

**Comment by flyingL123** [comment]
@junedkazi thanks again!

**Comment by junedkazi** [comment]
Happy to help. I am closing this since this issue is resolved.
